apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: webapp
spec:
  containers:
  - name: webapp
    image: 407373101635.dkr.ecr.us-east-1.amazonaws.com/assignment-1-app:v0.1
    env:
      - name: DBHOST
        value: "10.244.0.5"
      - name: DBPORT
        value: "3306"
      - name: DATABASE
        value: "employees"
      - name: DBPWD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: password
      - name: DBUSER
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: user
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always