apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
  namespace: sqldb
spec:
  containers:
  - image: 407373101635.dkr.ecr.us-east-1.amazonaws.com/assignment-1-db:v0.1
    name: mysql-db
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: password
    ports:
    - containerPort: 3306
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always