apiVersion: apps/v1
kind: ReplicaSet
metadata:
    labels:
        app: mysql
    name: mysql-db
    namespace: sqldb
spec:
    replicas: 3
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                -   image: 407373101635.dkr.ecr.us-east-1.amazonaws.com/assignment-1-db:v0.1
                    name: mysql-db
                    env:
                        -   name: MYSQL_ROOT_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: db-secrets
                                    key: password
                    ports:
                        - containerPort: 3306
            dnsPolicy: ClusterFirst
            restartPolicy: Always